# Generated by Django 4.2.4 on 2023-08-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=100)),
                ('body', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(max_length=200, unique_for_date='published')),
                ('published', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
